export const GridText = [ 
    "Birds don't pee",
    "Eggplants contain nicotine",
    "Babies can't dream",
    "Stars eat planets",
    "Fergie voiced Sally",
    "Turtles masturbate",
    "Jellyfish can evaporate",
    "Gold is edible",
    "Monkeys sometimes floss",
    "McDonald's does weddings",
    "Saturn rains diamonds",
    "Dolphins name themselves",
    "Swearing relaxes people",
    "Mangoes get sunburns",
    "Horses can't vomit",
    "Avocados are berries",
    "Lighters predate matches",
    "Sharks predate trees",
    "Wombats poop cubes",
    "Blood contains gold",
    "Orcas are dolphins",
    "Fish can cough",
    "Best programmer",
    "In love with React",
    "Must wake up early"
  ];